title: Manoa Bazaar
description: An application created to allow easy buying and selling of goods between students moving into or off of campus.
google_analytics:
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
